name: QA

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run tests
        run: pnpm test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run ESLint
        run: pnpm lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run typecheck
        run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run prettier
        run: pnpm format:check

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run Cypress tests
        uses: cypress-io/github-action@0da3c06ed8217b912deea9d8ee69630baed1737e # pin@v6.7.6
        with:
          start: pnpm start:bridge --host
          command: pnpm test:e2e:ci # TODO: consider running in --headless
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          spec: tests/e2e/specs/*
        env:
          SECRET_WORDS: 'test test test test test test test test test test test junk'
          NETWORK_NAME: bob
          RPC_URL: 'https://l2-fluffy-bob-7mjgi9pmtg.t.conduit.xyz'
          CHAIN_ID: 901
          SYMBOL: ETH
          BLOCK_EXPLORER: 'https://explorerl2-fluffy-bob-7mjgi9pmtg.t.conduit.xyz'

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          path: |
            apps/e2e/tests/e2e/videos
            apps/e2e/tests/e2e/screenshots
        continue-on-error: true
